name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production server..."
        # Add your deployment script or commands here
        ssh user@your-server "cd /path/to/your/app && git pull && npm install && npm run build && pm2 restart all"

    - name: Notify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"New deployment completed on production!"}' YOUR_SLACK_WEBHOOK_URL
